#!/bin/bash
#SBATCH -J SimpleMatcher
#SBATCH -p general
#SBATCH -o python%j.txt
#SBATCH -e python_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --time=168:00:00 
#SBATCH --mail-user=gklinge@iu.edu
#SBATCH --mail-type=BEGIN,END
#SBATCH --mem 100G
#SBATCH -A r00638
#SBATCH --array=1

module load python

python -m venv ~/myenv
source ~/myenv/bin/activate

pip install pandas rapidfuzz

assignee_csv_file="/N/u/gklinge/Quartz/Matching/assignees_unique_clean.csv"
csrp_csv_file="/N/u/gklinge/Quartz/Matching/crsp_file.csv"
output_folder="/N/u/gklinge/Quartz/Output/matched_output"
results_folder="/N/u/gklinge/Quartz/Output/results"

cd $SLURM_SUBMIT_DIR

srun python YourMatchingScript.py "$csrp_csv_file" "$assignee_csv_file" "$output_folder" "$results_folder"
